markdown: kramdown
permalink: /:year/:month/:day/:title/
url: http://hopehook.com
website-url: hopehook.com
name: HopeHook's Blog
website: HopeHook's House
author: stach.tan
email: achst@qq.com
duoshuo: hopehook
github: hopehook
weibo: hopehook
rouge: true
safe: true
paginate: 10
about: "这里是 HopeHook 的个人博客，欢迎你的到来。"
